# Use official Node.js image
FROM node:18-alpine AS deps
WORKDIR /app

# Install dependencies
COPY package.json package.json ./
RUN npm install --legacy-peer-deps

# Rebuild source code for production
FROM node:18-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

# Run stage
FROM node:18-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=8000

# Copy only necessary build artifacts
# COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

# Expose port
EXPOSE 8000

# Start Next.js
CMD ["npm", "start"]
